<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>My Game Launcher</Product>
    <Company>xasifsaeedx</Company>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GameLauncher.Core/GameLauncher.Core.csproj" />
    <ProjectReference Include="../GameLauncher.Infrastructure/GameLauncher.Infrastructure.csproj" />
  </ItemGroup>
</Project>
